services:
  iptv-webclient:
    image: ghcr.io/elazaroo/iptv-webclient:latest
    ports:
      - "3010:80"
    volumes:
      - iptv_data:/app/data
    environment:
      - FLASK_ENV=production
      - FLASK_APP=app/main.py
    restart: unless-stopped
    container_name: iptv-webclient

    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:80" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

volumes:
  iptv_data:
    driver: local
